### ISSUE TITLE
Cannot find type 'Data' in scope  -V 1.6.0

### ISSUE THREAD

**Issue by lrodriguezcds** [DevCycleHQ/ios-client-sdk#114]
Hi! I am getting the following error using version 1.6.0, any idea on how to fix this? I think you may need an import.. thanks
<img width="1032" alt="Screen Shot 2023-01-01 at 01 38 59" src="https://user-images.githubusercontent.com/46491828/210161162-7bc1ab31-de72-43da-8fbe-4fc2b98b0995.png">

**Comment by kaushalkapasi** [comment]
Hi @lrodriguezcds!

The Data type is part of Foundation, this issue should be resolved by cleaning & building your app project again! Let me know if this resolves the issue, otherwise we can investigate further

**Comment by lrodriguezcds** [comment]
Hi @kaushalkapasi ! Tried cleaning and building several times with no luck! mm maybe explicitly importing`Foundation` within the file that is using it is necessary? 

(Using Xcode 14.1 - Swift 5 and Xcode package manager to handle external dependencies)

Thank you!

**Comment by kaushalkapasi** [comment]
Thanks for getting me the extra info! The team is working on a fix and should have this resolved for you shortly!

**Comment by kaushalkapasi** [comment]
Hi @lrodriguezcds, we've published a new version `v1.6.1` with a fix for this issue.

Let us know once you have verified it and we can close this issue!
